# All settings are optional; these are the default values.

[usb]
default_baud_rate = 25_000

[device.Z8T]
vendor_id = 4_292
product_id = 60_000

[device.LK5-Pro]
vendor_id = 6_790
product_id = 29_987
baud_rate = 25_000  # optional

[discovery]
# Name of the printctl node, defaults to hostname
name = "client"

[server]
# The address the server will bind to
grpc_addr = '0.0.0.0'
# The port the server will listen on
grpc_port = 50051

[ui]
# Toggle dashboard web app
use_web = true
# The address the dashboard web app will bind to
http_addr = '0.0.0.0'
# The port the dashboard web app will listen on
http_port = 8080
