[package]
name = "printctl-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.29.0"
color-eyre = "0.6.5"
crossterm = "0.29.0"
gcode = "0.6.1"
ratatui-explorer = "0.2.1"
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["full"] }
